schema_version = "1.0.0"

id = "universal_custom_script_manager"
version = "2.1.0"
name = "Universal Custom Script Manager"
tagline = "Custom Scripts Manager"
maintainer = "maqq1e - github.com/maqq1e"
type = "add-on"

# # Optional: link to documentation, support, source files, etc
website = "https://github.com/maqq1e/CustomScriptManager"

tags = ["Pipeline", "System", "Development"]

blender_version_min = "5.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Load .json template file"